// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "context"
	_ "encoding/json"
	_ "fmt"
	_ "github.com/AbsaOSS/gopkg/env"
	_ "github.com/hashicorp/go-multierror"
	_ "github.com/julienschmidt/httprouter"
	_ "github.com/sirupsen/logrus"
	_ "github.com/spf13/cobra"
	_ "gopkg.in/yaml.v2"
	_ "html"
	_ "io/ioutil"
	_ "net/http"
	_ "net/url"
	_ "os"
	_ "runtime"
	_ "strconv"
	_ "sync"
	_ "time"
)
